ansys_c7_packages: [ libXp.x86_64, xorg-x11-fonts-cyrillic.noarch, xterm.x86_64, motif.x86_64, compat-libstdc++-33.x86_64, libstdc++.x86_64, libstdc++.i686, gcc-c++.x86_64, compat-libstdc++-33.i686, libstdc++-devel.x86_64, libstdc++-devel.i686, compat-gcc-44.x86_64, gtk2.i686, libXxf86vm.i686, libSM.i686, libXt.i686, libXt, xorg-x11-fonts-ISO8859-1-75dpi.noarch, libgcc.i686, libgcc, libXau.i686, libXau,  libxcb.i686, libxcb, glibc.i686,  glibc, libX11, libX11.i686, compat-libtiff3, libpng12, expectk, tk, perl,  mesa-libGLU-devel, motif-devel, libXp-devel, libXt-devel, libXext-devel, libXi-devel, libX11-devel, libSM-devel, libICE-devel ]
#ensure the prerequs are installed (note there is some overlap but this just makes like easier to correlate to the ansys manual)
#see https://install.simutechgroup.com/info-required-linux-packages-and-libraries
##Plus ANSYS_Inc._Installation_Guides.pdf (for 23r2 used as reference))
ansys_r8_packages: ['alsa-lib', 'aspell', 'atk', 'at-spi2-atk', 'at-spi2-core', 'audit-libs', 'avahi-libs', 'brotli', 'bzip2-libs', 'cairo', 'cairo-gobject', 'compat-hwloc1', 'compat-libgfortran-48', 'compat-openssl10', 'cups-libs', 'cyrus-sasl-lib', 'dbus-libs', 'elfutils-libelf', 'enchant2', 'expat', 'flac-libs', 'fontconfig', 'freetype', 'fribidi', 'gdk-pixbuf2', 'glib2', 'glibc', 'glibc-devel', 'glibc.i686', 'gmp', 'gnutls', 'graphite2', 'gsm', 'gstreamer1', 'gstreamer1-plugins-base', 'gtk2', 'gtk3', 'gzip', 'harfbuzz', 'harfbuzz-icu', 'hyphen', 'jbigkit-libs', 'keyutils-libs', 'krb5-libs', 'libasyncns', 'libatomic', 'libblkid', 'libcap', 'libcap-ng', 'libcom_err', 'libcurl', 'libcurl-devel', 'libdatrie', 'libdrm', 'libepoxy', 'libffi', 'libfontenc', 'libgcc', 'libgcc.i686', 'libgcrypt', 'libgfortran', 'libglvnd', 'libglvnd-egl', 'libglvnd-gles', 'libglvnd-glx', 'libglvnd-glx.i686', 'libglvnd-opengl', 'libgomp', 'libgpg-error', 'libibverbs', 'libICE', 'libICE-devel', 'libICE.i686', 'libicu', 'libicu50', 'libidn2', 'libjpeg-turbo', 'libmount', 'libnghttp2', 'libnl3', 'libnotify', 'libnsl', 'libogg', 'libpciaccess', 'libpng', 'libpng12', 'libpsl', 'libquadmath', 'librdmacm', 'libreoffice-ure', 'libsecret', 'libselinux', 'libSM', 'libSM-devel', 'libSM.i686', 'libsndfile', 'libsoup', 'libssh', 'libstdc++', 'libstdc++.i686', 'libtasn1', 'libthai', 'libtheora', 'libtiff', 'libunistring', 'libuuid', 'libuuid-devel', 'libuuid.i686', 'libvorbis', 'libwayland-client', 'libwayland-cursor', 'libwayland-egl', 'libwayland-server', 'libwebp', 'libX11', 'libX11-devel', 'libX11.i686', 'libX11-xcb', 'libXau', 'libXau.i686', 'libxcb', 'libxcb.i686', 'libXcomposite', 'libxcrypt', 'libXcursor', 'libXdamage', 'libXdmcp', 'libXext', 'libXext-devel', 'libXext.i686', 'libXfixes', 'libXft', 'libXi', 'libXi-devel', 'libXinerama', 'libxkbcommon', 'libxkbcommon-x11', 'libxml2', 'libXmu', 'libXp', 'libXp-devel', 'libXrandr', 'libXrender', 'libxshmfence', 'libxslt', 'libXt', 'libXt-devel', 'libXt.i686', 'libXtst', 'libXxf86vm', 'libzstd', 'lsb', 'lz4-libs', 'mesa-libgbm', 'mesa-libGLU', 'mesa-libGLU-devel', 'motif', 'motif-devel', 'ncurses-libs', 'nettle', 'nspr', 'nss', 'nss-softokn', 'nss-softokn-freebl', 'nss-util', 'numactl-libs', 'ocl-icd', 'openjpeg2', 'openldap', 'openssl-libs', 'orc', 'p11-kit', 'pam', 'pango', 'pcre', 'pcre2', 'pcre2-utf16', 'perl-devel', 'pixman', 'pulseaudio-libs', 'pulseaudio-libs-glib2', 'systemd-libs', 'tar', 'ucx', 'webkit2gtk3', 'webkit2gtk3-jsc', 'which', 'woff2', 'xcb-util', 'xcb-util-image', 'xcb-util-keysyms', 'xcb-util-renderutil', 'xcb-util-wm', 'xorg-x11-fonts-100dpi', 'xorg-x11-fonts-75dpi', 'xterm', 'xz-libs', 'zlib', 'json-glib', 'hwloc-libs', 'libXScrnSaver', 'pciutils-libs',  'libstemmer']
ansys_192_packages: 
  - libpng12
  - libXp.x86_64
  - xorg-x11-fonts-cyrillic.noarch
  - xterm.x86_64
  - compat-libstdc++-33.x86_64
  - libstdc++.x86_64
  - libstdc++.i686
  - gcc-c++.x86_64
  - compat-libstdc++-33.i686
  - libstdc++-devel.x86_64
  - libstdc++-devel.i686
  - gtk2.i686
  - libXxf86vm.i686
  - libSM.i686
  - libXt.i686
  - xorg-x11-fonts-ISO8859-1-75dpi.noarch
  - compat-glibc
  - glibc.i686
  - glib2.i686
  - bzip2-libs.i686
  - libpng.i686
  - libtiff.i686
  - libXft.i686
  - libXxf86vm.i686
  - libpng12
  - libpng12.i686
  - libXScrnSaver
  - compat-libtiff3.i686
  - compat-libtiff3
grub_options:  
 - option: "systemd.firstboot"
   value: "off"
