#!/bin/bash

#
# Check the system storage components via omreport
#
# Andrew Harford <andrew.harford@securelinx.com>
#

VIRTWHAT=/usr/sbin/virtwhat

if [ -x $VIRTWHAT ]; then
  platform=$($VIRTWHAT)
  if [ -n "$platform" ]; then
    echo "Platform is $platform"
    exit 0
  fi
fi


OMREPORT=/opt/dell/srvadmin/bin/omreport

if [ ! -x $OMREPORT ]; then
  echo "Could not locate $OMREPORT"
  exit 3 
fi

rc=0

components="$($OMREPORT storage vdisk | grep "Status  " |tr '\n' '@')"

while read -d '@' -r component; do
  status=$(echo $component | awk '{print $3}')
  if [ "$status" != "Ok" ]; then
    rc=2
    output="Vdisk $status"
  fi
done <<< $components

if [ $rc -eq 0 ]; then
  output="All vdisks OK"
fi

echo $output
exit $rc
