* soft nofile 10240
* hard nofile 10240
* soft memlock unlimited
* hard memlock   unlimited
* soft nofile 10240
* hard nofile 10240
* soft nproc  8192
* hard mproc 8192
#ansys 202 1024000
* soft stack 1024000
* hard stack  1024000

