[domain/default]

autofs_provider = ldap
cache_credentials = True
ldap_search_base = ou=groups,dc=host,dc=ulster,dc=ac,dc=uk
id_provider = ldap
auth_provider = ldap
chpass_provider = ldap
ldap_uri = ldaps://cfd6.host.ulster.ac.uk
ldap_id_use_start_tls = True
ldap_tls_cacertdir = /etc/openldap/cacerts
enumerate = True
ldap_tls_reqcert = allow
ldap_id_use_start_tls = True
ldap_user_search_base = ou=People,dc=host,dc=ulster,dc=ac,dc=uk
ldap_schema = rfc2307bis
ldap_group_member = uniqueMember

[sssd]
services = nss, pam, autofs

domains = default
[nss]
homedir_substring = /home

[pam]

[sudo]

[autofs]

[ssh]

[pac]

[ifp]

[secrets]

[session_recording]

