#!/usr/bin/env python

from __future__ import print_function
import sys, os, re
def parse_report(quotafile):
   f = open(quotafile)
   start=0
   usage_dict={}
   for line in f:
     if len(line)<2: continue
     if "----------" in line:
       start=1
       continue
     if start == 0: continue
     

     x=re.split("[\s]*", line)
     user=x[0]
     usage=(x[1]) 
     #print usage
     usage_dict[user]=int(usage)
   return usage_dict     
usage_stats = {'Total':{}}
all_user=[]

for root, dir, files in os.walk("/apps/usage"):
   if "latest_kbytes" not in files: continue
   node=os.path.basename(root)
   #print (node, files)
   usage_stats_node=parse_report (os.path.join(root,"latest_kbytes"))
   if node not in usage_stats:
       usage_stats[node]=usage_stats_node
   for user in usage_stats_node: 
       if user not in all_user:
          all_user.append(user)
   for ( user, userstats ) in usage_stats_node.items():
         #print user, userstats
         
         if user not in usage_stats['Total']:
             usage_stats['Total'][user]=0
         #print userstats, int(userstats)
         usage_stats['Total'][user]+=int(userstats)
     

print ( '{0:12s},'.format("User"), end =" " )

for node in sorted(usage_stats.keys()):
      print ('{0:>9s},'.format(node), end =" ")


for user in all_user:
   print ()
   print ("{0:12s},".format(user),end =" " ) 
   for node in sorted(usage_stats.keys()):
      if user in usage_stats[node]:
         print ( '{0:8d}M,'.format( usage_stats[node][user]/1024 ).ljust(8),end =" " )

      else:
         print ( '{0:8d}M,'.format(0).ljust(8) ,end =" ")

print()
